{% set name = "vsc-install" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vsc-install-{{ version }}.tar.gz
  sha256: 825f43a63b0a5ee29b743cd87601c4abfe29d4493ae120a01b2531809b42a26e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - mock
    - prospector >=0.12.1
    - pylint
    - python >=3.6
    - setuptools <42.0

test:
  imports:
    - vsc
    - vsc.install
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hpcugent/vsc-install
  summary: vsc-install provides shared setuptools functions and classes for python libraries developed by UGent's HPC group
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anthchirp
    - boegel
    - jerowe
