{% set version = "0.12.9" %}

package:
  name: vsc-install
  version: {{ version }}

source:
  fn: vsc-install-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/v/vsc-install/vsc-install-{{ version }}.tar.gz
  sha256: 495a8c27a5dd66b4c31dfbe87cb173cd16dfb91a2445296cb209c3e30945f91f

build:
  preserve_egg_dir: True
  number: 0
  skip: True  # [win or py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - certifi 2016.9.26
    - mock
    - prospector >=0.12.1
    - pylint

  run:
    - python
    - setuptools
    - certifi 2016.9.26
    - mock
    - prospector >=0.12.1
    - pylint

test:
  imports:
    - vsc
    - vsc.install

about:
  home: https://github.com/hpcugent/vsc-install
  license: LGPL-2.0
  license_file: LICENSE
  summary: "vsc-install provides shared setuptools functions and classes for python libraries developed by UGent's HPC group."
  license_family: LGPL

extra:
  recipe-maintainers:
    - jerowe
    - boegel
