{% set version = "0.16.0" %}

package:
  name: vsc-install
  version: {{ version }}

source:
  fn: vsc-install-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/v/vsc-install/vsc-install-{{ version }}.tar.gz
  sha256: 0ed0213e79b094999b5b90b0c492dd38de3d240ff229bfbe9b775183bdc8040c

build:
  preserve_egg_dir: true
  number: 0
  skip: true  # [win or py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - certifi 2016.9.26
    - mock
    - prospector >=0.12.1
    - pylint

  run:
    - python
    - setuptools
    - certifi 2016.9.26
    - mock
    - prospector >=0.12.1
    - pylint

test:
  imports:
    - vsc
    - vsc.install

about:
  home: https://github.com/hpcugent/vsc-install
  license: LGPL-2.0
  license_file: LICENSE
  summary: vsc-install provides shared setuptools functions and classes for python libraries developed by UGent's HPC group.
  license_family: LGPL

extra:
  recipe-maintainers:
    - jerowe
    - boegel
